persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type all

listener 1883
allow_anonymous true

max_keepalive 65535
max_inflight_messages 20
retry_interval 10
sys_interval 60

message_size_limit 0
max_queued_messages 1000
